INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 25,'ON');
INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 30,'OFF');
INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 50,'ON');
INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (4, 0,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 30,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 33,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (3, 60,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (4, 10,'OFF');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (1, 1, 1);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (2, 2, 2);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (3, 3, 3);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (4, 4, 4);

